config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  resources :startups, only: [:index, :show, :new, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/startup.rb
class Startup < ApplicationRecord
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/startups_controller.rb
require 'open-uri'
require 'nokogiri'


class StartupsController < ApplicationController
  def index
    @startups = Startup.all
  end

  def show
    @startup = Startup.find(params[:id])

    # startuptoshow = Startup.where(name: @startup.name)
    # startuptoshow = Startup.last
    nameto = @startup.name.downcase

    # url = "https://www.crunchbase.com/organization/#{name}"
    url = "https://www.welcometothejungle.co/companies/#{nameto}"

    html_file = open(url).read
    html_doc = Nokogiri::HTML(html_file)


    counter = 0
    element = []
    html_doc.search('.sc-laTMn.fxLISD').each do |elt|
      if counter<2
        element << elt.text.strip
        counter += 1
      end
    end


    creation = element[0]
    effectif = element[1]
    @startup.update(creation: creation)
    @startup.update(people: effectif)


    counter = 0
    city_array = []
    html_doc.search('.sc-cbkKFq.eeLAkK').each do |elt|
     if counter<2
        city_array << elt.text.strip
        counter += 1
      end
    end

    city = city_array[1]
    @startup.update(address: city)

    puts creation
    puts effectif
    puts city

    counter = 0
    description_array = []
    html_doc.search('.sc-iQNlJl.hRSbQZ p').each do |elt|
      if counter < 1
        description_array << elt.text.strip
        counter += 1
      end
    end
    description = description_array[0]
    puts description
    @startup.update(activity: description)
  end

  def new
    @startup = Startup.new
  end

  def create
    @startup = Startup.new(startup_params)
    if @startup.save
      redirect_to startup_path(@startup)
    else
      render "new"
    end
  end

  def update
  end

  private

  def startup_params
    params.require(:startup).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>screening tool</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- formulaire d'entrée -->
<%# form_tag startups_path, class:"new-search", method: :get do %>
  <!-- <div class="banner">
    <h1>Look for a startup</h1>
    <div class="row">
      <div class="form-group col-md-offset-3 col-md-6"> -->
        <%# text_field_tag :name, params[:name], placeholder: "Facebook", class:"form-control" %>
        <%# submit_tag value="start now", class:"btn" %>
 <!--      </div>
    </div>
  </div> -->
<%# end %>

<div class="container">
  <h1>Welcome to the screening tool</h1>
  <%= link_to "start now", new_startup_path, class: "btn btn-primary" %>
</div>

app/views/startups/index.html.erb
<div class="container banner">
  <% @startups.each do |startup| %>
  <h2><%= startup.name %></h2>
<% end %>
</div>

app/views/startups/new.html.erb
<div class="container">
  <%= simple_form_for [@startup] do |f| %>
  <%= f.input :name %>
  <%= f.submit "launch", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/startups/show.html.erb
<div class="container banner">
  <h1> <%= @startup.name %></h1>
  <h2> <%= @startup.creation %></h2>
  <h2> <%= @startup.address %></h2>
  <h2> <%= @startup.people %> personnes </h2>
  <h2> <%= @startup.activity %></h2>
</div>

app/views/startups/update.html.erb
<h1>Startups#update</h1>
<p>Find me in app/views/startups/update.html.erb</p>